#!/bin/bash

PIPE=/tmp/autotoum_$$
ATOUM=bin/atoum
SOURCES="$(pwd)/src $(pwd)/tests/units"
BACKGROUND=false

check() {
	if [ ! $(which kicker) ]
	then
		echo -e " kicker is not available. Consider installing kicker's gem"

		exit 1
	fi
}

usage() {
	echo -e " Usage : $(basename $0) [-h] [-d] [-q] [-b path/to/atoum] [-w path/to/sources] [-- extra-args]"
	echo -e "     -h : Display this message"
	echo -e "     -q : Quiet mode (no output)"
	echo -e "     -d : Background mode (no output)"
	echo
	echo -e "     Path to atoum : path to atoum executable (defaults to $ATOUM)"
	echo -e "     Path to sources : the watched files and/or directories (defaults to $SOURCES)"
	echo -e "     Extra arguments : Extra arguments are forwarded to the atoum executable"
	echo
	echo -e "     You can specify several files/directories to watch using a comma (,) separated list:"
	echo -e "         $ autotoum -w src,tests/units/subset,tests/units/otherSubset -- -d tests/units"
	echo -e "         # Use CTRL+C to quit"
	echo
	echo -e "     Background mode:"
	echo -e "         $ autotoum -d -w src,tests/units/subset,tests/units/otherSubset -- -d tests/units"
	echo -e "         $ ..."
	echo -e "         $ autotoum stop"

	check
}

atoum() {
    bash $AUTOTOUM_SCRIPT
}

watch() {
    kicktrap() {
        stty echo;
        unwatch $PIPE;
    }

    trap kicktrap INT

    kicker -l 0 -s -e "echo > $PIPE" $SOURCES > /dev/null 2>&1 &
    echo $! > .autotoum

    if [ ! -x $ATOUM ]
    then
        echo "Cannot run $ATOUM"

        exit 1
    fi

    LOOP=false
    while true
    do
        if read line > /dev/null 2>&1 < $PIPE
        then
            if $LOOP
            then
                echo
            else
                LOOP=true
            fi
        fi
    done | atoum $*
}

unwatch() {
    if [ -f .autotoum ]
    then
        while read pid
        do
            kill -9 $pid > /dev/null 2>&1
        done < .autotoum

        rm ./.autotoum
    else
        echo -e "autotoum is not running"

        exit 1
    fi

    [[ -p $PIPE ]] && rm $PIPE

    exit 0
}

while getopts “hqdb:w:” OPTION
do
    case $OPTION in
        h)
            usage
            exit 0
            ;;
        q | d)
            atoum() {
                bash $AUTOTOUM_SCRIPT > /dev/null 2>&1
            }

            [ "$OPTION" = "d" ] && BACKGROUND=true
            ;;
        b)
            ATOUM=$OPTARG
            ;;
        w)
            SOURCES=$(echo $OPTARG | sed "s/,/ /g")
            for entry in $SOURCES
            do
                if [ ! -d $entry ] && [ ! -f $entry ]
                then
                    echo "Directory/File $entry does not exist"
                    exit 1
                fi
            done
            ;;
        ?)
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ "$1" = "stop" ]
then
    unwatch $PIPE
else
    if [ -f .autotoum ]
    then
        echo -e "autotoum is already running here"

        exit 1
    fi

    shift $(expr $OPTIND - 1)

    check

    AUTOTOUM_SCRIPT=$(mktemp -t autotoum)
    echo $ATOUM $@ --loop > $AUTOTOUM_SCRIPT

    [[ -p $PIPE ]] && rm $PIPE; mkfifo $PIPE

    stty -echo

    if [ $BACKGROUND = true ]
    then
        watch $* &
        echo $! > .autotoum
    else
        watch $*
    fi

    stty echo
fi


