#!/usr/bin/env php
<?php
define('INSTALLER_URL',            'https://raw.github.com/jubianchi/autotoum/master/installer');
define('AUTOTOUM_GIT_URL_DEFAULT', 'https://raw.github.com/jubianchi/autotoum/master/autotoum');
define('AUTOTOUM_GIT_URL',         (($url = getenv('AUTOTOUM_GIT_URL')) ? $url : AUTOTOUM_GIT_URL_DEFAULT));

define('AUTOTOUM_PATH_DEFAULT',    '/usr/share');
define('AUTOTOUM_PATH',            (($path = getenv('AUTOTOUM_PATH')) ? $path : AUTOTOUM_PATH_DEFAULT) . DIRECTORY_SEPARATOR . 'autotoum');
define('AUTOTOUM_SYMLINK_DEFAULT', '/usr/local/bin');
define('AUTOTOUM_SYMLINK',         (($symlink = getenv('AUTOTOUM_SYMLINK')) ? $symlink : AUTOTOUM_SYMLINK_DEFAULT) . DIRECTORY_SEPARATOR . 'autotoum');

if(false === defined('STDOUT')) {
    define('STDOUT', fopen('php://stdout', 'w'));
}

if(false !== getenv('AUTOTOUM_PATH') || false !== getenv('AUTOTOUM_SYMLINK')) {
    $argv[] = '--global';
}

$silence = false;
$errors = array (
    E_ERROR             => 'ERROR',
    E_WARNING           => 'WARNING',
    E_PARSE             => 'PARSING ERROR',
    E_NOTICE            => 'NOTICE',
    E_CORE_ERROR        => 'CORE ERROR',
    E_CORE_WARNING      => 'CORE WARNING',
    E_COMPILE_ERROR     => 'COMPILE ERROR',
    E_COMPILE_WARNING   => 'COMPILE WARNING',
    E_USER_ERROR        => 'USER ERROR',
    E_USER_WARNING      => 'USER WARNING',
    E_USER_NOTICE       => 'USER NOTICE',
    E_STRICT            => 'STRICT NOTICE',
    E_RECOVERABLE_ERROR => 'RECOVERABLE ERROR'
);

error_reporting(0);
set_error_handler(function($code, $str, $file, $line) use($errors, &$silence) {
    if(false === $silence) {
        printfln('<red>> [%s] %s (Line %d)', $errors[$code], $str, $line);
    }
});

array_shift($argv);
exit(execute($argv, $silence));

function execute(array $args, &$silence) {
    printfln('> <green>autotoum installer');
    printfln('> <blue>atoum auto-loop mode');

    if(true === in_array('--usage', $args)) {
        usage($args);

        return 0;
    }

    printfln('>> <yellow>Checking requirements...');
    $silence = true;
    if(false === checkRequirements($args)) {
        return 1;
    }
    $silence = false;

    if(true === in_array('--check', $args)) {
        return 0;
    }

    if(false === download($args)) {
        return 1;
    }

    install($args);

    printfln('>> <green>autotoum was successfully installed. Enjoy!');

    return 0;
}

function usage(array $args) {
    $format = '%-15s : %s';
    printfln($format, '--global', 'Install autotoum as a global command');
    printfln($format, '--check', 'Only run system requirements check');

    printfln(PHP_EOL . 'Environment :');
    printfln($format, 'AUTOTOUM_GIT_URL', 'Git repository <yellow>(default : ' . AUTOTOUM_GIT_URL_DEFAULT . ')');
    printfln($format, 'AUTOTOUM_PATH', 'Installation directory <yellow>(implies --global, default : ' . AUTOTOUM_PATH_DEFAULT . ')');
    printfln($format, 'AUTOTOUM_SYMLINK', 'autotoum bin symlink path <yellow>(implies --global, default: ' . AUTOTOUM_SYMLINK_DEFAULT . ')');

    printfln(PHP_EOL . 'Examples :');
    printfln('$ curl ' . INSTALLER_URL .' | sudo php -- --global');
    printfln('$ curl ' . INSTALLER_URL .' | AUTOTOUM_PATH=/home/me php');
}

function download(array $args) {
    printfln('>> <yellow>Installing from sources...');

    if(true === in_array('--global', $args)) {
        $path = AUTOTOUM_PATH;
    } else {
        $path = getcwd() . DIRECTORY_SEPARATOR . 'autotoum';
    }

    if(false === checkDirectoryExists($path)) {
        checkAndCreateDirectory($path);
    }

    printfln('>>> <yellow>Downloading autotoum...');
    file_put_contents(
        $path . DIRECTORY_SEPARATOR . basename(AUTOTOUM_GIT_URL),
        file_get_contents(AUTOTOUM_GIT_URL)
    );

    return true;
}

function install(array $args) {
    if(true === in_array('--global', $args)) {
        if(true === checkLinkExists(AUTOTOUM_SYMLINK)) {
            unlink(AUTOTOUM_SYMLINK);
        }
        ppassthru('ln -s ' . AUTOTOUM_PATH . DIRECTORY_SEPARATOR .'autotoum ' . AUTOTOUM_SYMLINK);
        ppassthru(sprintf('chmod +x %s', AUTOTOUM_SYMLINK));

        printfln('>> <green>autotoum home : <yellow>' . AUTOTOUM_PATH);
        printfln('>> <green>autotoum bin path : <yellow>' . AUTOTOUM_PATH . DIRECTORY_SEPARATOR .'autotoum -> ' . AUTOTOUM_SYMLINK);
    } else {
        ppassthru(sprintf('chmod +x %s/autotoum/autotoum', getcwd()));

        printfln('>> <green>autotoum home : <yellow>%s/autotoum', getcwd());
        printfln('>> <green>autotoum bin path : <yellow>%s/autotoum/autotoum', getcwd());
    }
}

function checkRequirements(array $args) {
    $error = false;

    if(ppassthru('which ruby') !== 0) {
        printfln('>>> <red>Ruby is not installed');
        $error = true;
    } else {
        exec('ruby -v', $output);

        printfln('>>> <green>Actual Ruby version is %s', $output[0]);
    }

    if(ppassthru('which kicker') !== 0) {
        printfln('>>> <red>Kicker is not installed');
        printfln('>>> <red>Please run: gem install --version=\'< 2.6\' kicker');
        $error = true;
    } else {
        $output = null;
        exec('kicker -v', $output);

        printfln('>>> <green>Actual Kicker version is %s', $output[0]);
    }

    if(false === checkPermissions($args)) {
        $error = true;
    } else {
        $paths = getPaths($args);
        $paths = implode(', ', array_keys(array_filter($paths, function($v) { return (true === $v);  })));
        printfln('>>> <green>You have required permissions on <yellow>%s', $paths);
    }

    return (false === $error);
}

function checkPermissions(array $args) {
    if(false != ($restrict = ini_get('open_basedir'))) {
        printfln('>>> <yellow>open_basedir restriction : %s', $restrict);
        printfln('>>>> To fix this issue, try to run :');
        printfln('>>>> <yellow>AUTOTOUM_PATH=/an/allowed/path ./installer <clear>or <yellow>curl ' . INSTALLER_URL . ' | AUTOTOUM_PATH=/an/allowed/path php');
        printfln('>>>> or');
        printfln('>>>> <yellow>php -dopen_basedir= ./installer <clear>or <yellow>curl ' . INSTALLER_URL . ' | php -dopen_basedir=');
    }

    $paths = getPaths($args);

    if(true === in_array(false, $paths)) {
        $paths = implode(', ', array_keys(array_filter($paths, function($v) { return (false === $v);  })));
        printfln('>>> <red>You don\'t have required permissions on <yellow>%s', $paths);

        return false;
    }

    return true;
}

function getPaths(array $args) {
    if(true === in_array('--global', $args)) {
        $paths = array(
            dirname(AUTOTOUM_SYMLINK) => is_writeable(dirname(AUTOTOUM_SYMLINK)),
            dirname(AUTOTOUM_PATH) => is_writeable(dirname(AUTOTOUM_PATH))
        );
    } else {
        $paths = array(
            getcwd() => is_writeable(getcwd())
        );
    }

    return $paths;
}

function checkDirectoryExists($dir) {
    if(false === ($exists = is_dir($dir))) {
        printfln('>>> <yellow>Directory %s does not exist.', $dir);
    } else {
        printfln('>>> <yellow>Directory %s exists.', $dir);
    }

    return $exists;
}

function checkAndCreateDirectory($dir) {
    if(false === checkDirectoryExists($dir)) {
        printfln('>>> <yellow>Creating directory %s', $dir);
        mkdir($dir, 0755, true);
    }
}

function checkFileExists($file) {
    if(false === ($exists = is_file($file))) {
        printfln('>>> <yellow>File %s does not exist.', $file);
    } else {
        printfln('>>> <yellow>File %s exists.', $file);
    }

    return $exists;
}

function checkLinkExists($file) {
    if(false === ($exists = is_link($file))) {
        printfln('>>> <yellow>Symlink %s does not exist.', $file);
    } else {
        printfln('>>> <yellow>Symlink %s exists.', $file);
    }

    return $exists;
}

function ppassthru($cmd) {
    printfln('>>> <yellow>' . $cmd);

    $status = 0;
    passthru($cmd, $status);

    return $status;
}

function printfln($line) {
    $line = call_user_func_array('sprintf', func_get_args());

    $support = '\\' === DIRECTORY_SEPARATOR ? false !== getenv('ANSICON') : (function_exists('posix_isatty') && true === posix_isatty(STDOUT));

    $colors = array(
        'red' => 31,
        'green' => 32,
        'yellow' => 33,
        'blue' => 34
    );
    $pattern = '/\<(' . implode('|', array_keys($colors)) . '|clear)\>/';

    if(true === $support) {
        $line = preg_replace_callback(
            $pattern,
            function($matches) use($colors) {
                $color = $matches[1];

                if('clear' === $color) {
                    return "\033[0m";
                } else {
                    return true === isset($colors[$matches[1]]) ? "\033[0;" . $colors[$matches[1]] . 'm' : '';
                }
            },
            $line
        );

        $line .= "\033[0m";
    } else {
        $line = preg_replace($pattern, '', $line);
    }

    $line .= PHP_EOL;

    print $line;
}